class_name RiderSkinDef
extends Resource
## Data-driven rider skin: suit/helmet colors plus optional decal textures.
##
## Colors are multiplied over the per-bike rider colors from the BikeDef: a
## Color with alpha == 0 means "inherit the default" (BikeDef color or a value
## derived from the suit). Decal art is generated by
## tools/assetgen/gen_rider_skins.py as a black-background luminance pattern
## converted to RGBA (white RGB, pattern in the alpha channel), so the runtime
## material tints it with `accent_color` and alpha-blends it over the suit.
##
## Unlock rules live here (progression) while shop prices live in
## Game.SHOP_SKINS alongside SHOP_BIKES. A default instance is a safe fallback
## when a .tres definition is missing.

const DEFAULT_PATH := "res://assets/data/skins/stock.tres"

@export var id := "stock"
@export var display_name := "Stock"

@export_group("Colors")
## Each color: alpha 0 inherits the default (BikeDef rider color / derived).
@export var suit_color := Color(0, 0, 0, 0)
@export var accent_color := Color(0, 0, 0, 0)
@export var helmet_color := Color(0, 0, 0, 0)
@export var glove_color := Color(0, 0, 0, 0)
@export var boot_color := Color(0, 0, 0, 0)
@export var visor_color := Color(0, 0, 0, 0)

@export_group("Decals")
## Directory with the decal art (res://assets/skins/<id>).
@export var decal_dir := ""
@export var decal_suit := "decal.png"    # chest emblem
@export var decal_helmet := ""           # helmet art; empty falls back to suit
@export var decal_scale := 1.0

@export_group("Unlock")
## Free-for-all when no rule matches; progression gates below.
@export var unlock_races := -1           # >= 0: open after N finished races
@export var unlock_boss := ""            # != "": open after beating that boss


## True when the color is meant to override the default (alpha > 0).
func overrides(c: Color) -> bool:
	return c.a > 0.0


func suit_decal_path() -> String:
	return _join(decal_suit)


func helmet_decal_path() -> String:
	var name := decal_helmet if decal_helmet != "" else decal_suit
	return _join(name)


func has_decals() -> bool:
	var path := suit_decal_path()
	return path != "" and ResourceLoader.exists(path)


func _join(file: String) -> String:
	if decal_dir == "" or file == "":
		return ""
	return "%s/%s" % [decal_dir, file]


static func load_default() -> RiderSkinDef:
	if ResourceLoader.exists(DEFAULT_PATH):
		var res := load(DEFAULT_PATH) as RiderSkinDef
		if res != null:
			return res
	return RiderSkinDef.new()
